* [32madditional-fields[m
  api-integration/hatchit[m
  api-integration/login[m
  api-integration/manage-loans[m
  api-intgeration-server/symph-api[m
  dashboard/task/feature[m
  dev[m
  feature/Quick-Cash-Loan[m
  feature/apply-loan-receipt-uniformity[m
  feature/apply-loan-submit[m
  feature/create-cookie-getter[m
  feature/create_receipt_page[m
  feature/housing-loan[m
  feature/loan-type[m
  feature/loan-type-new[m
  feature/login-otp[m
  feature/manage-loan-btn-nav[m
  feature/manage-loan-cards[m
  feature/manage-loan-download-btn[m
  feature/manage-loan-function-navigation[m
  feature/manage-loan-polish-page[m
  feature/manage-loan-redirect[m
  feature/manage-loan-responsive-page[m
  feature/manage-loan-reuse-layout-comp[m
  feature/manage-loans-details[m
  feature/manage-loans-loantype[m
  feature/otp-timer[m
  feature/phase2-genereate-code[m
  feature/rectify-generated-code[m
  feature/restrictions[m
  master[m
  upstream[m
